workflows:
  ios-workflow:
    name: Build iOS app
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install Ruby 2.7.0
        script: |
          brew install ruby@2.7
          echo 'export PATH="/usr/local/opt/ruby@2.7/bin:$PATH"' >> ~/.bash_profile
          echo 'export LDFLAGS="-L/usr/local/opt/ruby@2.7/lib"' >> ~/.bash_profile
          echo 'export CPPFLAGS="-I/usr/local/opt/ruby@2.7/include"' >> ~/.bash_profile
          source ~/.bash_profile
          ruby -v
      - name: Install CocoaPods
        script: |
          sudo gem install cocoapods
          cd ios
          pod install
      - name: Build iOS app
        script: flutter build ipa --release
    artifacts:
      - build/ios/ipa/**/*.ipa
